title: Cpt-Dingus' notes
description: I post stuff that might be useful to others here
theme: just-the-docs

url: https://cpt-dingus.github.io
baseurl: "/Obsidian-notes" 

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template